### ISSUE TITLE
AbstractModel is Assuming the ID is Numeric but is Typing it as a String

### ISSUE THREAD

**Issue by bird-man** [herculesinc/pg-dao#1]
The buildUpdateQuery and buildDeleteQuery functions in AbstractModel are not placing single quotes around the ${model.id} in the where clause, but in AbstractModel the id is typed as a string.  If you are using a non-numeric id, like a UUID the statements fail.

**Comment by irakliy81** [comment]
Thanks! This was kind of an "intentional" bug. The thing is that in the project for which I wrote pg-dao, all IDs are 64-bit integers (bigint). On the JS side, they are always treated as strings, but in the database they are numbers. So, the current code is working fine for me.

However, I think I can just add single quotes in the methods you mentioned, and it will work fine both for bigints and for strings (Postgres should automatically cast strings to integers). I'll look into this in the next day or two, and hopefully, will have a fix soon.

**Comment by irakliy81** [comment]
Just published v0.6.3 - the issue should be fixed there.

**Comment by bird-man** [comment]
Thanks that did the trick.  I appreciate your prompt response.
